#ifndef TIMESERIESPROVIDERCOMPONENT_GLOBAL_H
#define TIMESERIESPROVIDERCOMPONENT_GLOBAL_H


#include <QtCore/qglobal.h>

#ifdef TIMESERIESPROVIDERCOMPONENT_LIBRARY
# define TIMESERIESPROVIDERCOMPONENT_EXPORT Q_DECL_EXPORT
#else
# define TIMESERIESPROVIDERCOMPONENT_EXPORT //Q_DECL_IMPORT
#endif


#endif // TIMESERIESPROVIDERCOMPONENT_GLOBAL_H
